# also change Cargo.toml when changing this file, workaround for package name and extension-module
# only difference between this and Cargo.toml must be in: package.name, package.version, lib.name, lib.crate-type, workspace, dependencies.pyo3
[package]
name = "nnsplit"
version = "0.5.9-post0"
authors = ["Benjamin Minixhofer <bminixhofer@gmail.com>"]
edition = "2018"

[package.metadata.maturin]
requires-dist = ["onnxruntime==1.15.0", "tqdm>=4"]

[lib]
name = "nnsplit"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.15.0"
numpy = "0.14.1"
lazy_static = "1.4"
serde_json = "1.0"

[dependencies.nnsplit]
path = "../../nnsplit"
default-features = false
features = ["model-loader"]

[dependencies.pyo3]
version = "0.14"
features = ["extension-module"]

[workspace]
