name: Deploy to Github Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: write  # for JamesIves/github-pages-deploy-action to push changes in repo
    runs-on: ubuntu-latest
    env:
      module-working-directory: bindings/javascript
      website-working-directory: website

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3.3.0
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v2-beta
        with:
          node-version: '16'

      - name: Build module
        run: npm install && npm run build
        working-directory: bindings/javascript

      - name: Copy models
        run: cp -r models website/public/models

      - name: Build website
        run: npm ci && npm run build
        working-directory: website

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6 # releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: website/dist
          GIT_CONFIG_NAME: Github Action
          GIT_CONFIG_EMAIL: action@github.com